import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  OneToMany,
  JoinColumn,
  Index,
} from 'typeorm';
import { Farm } from '../farms/farm.entity';
import { TaskAssignee } from './task-assignee.entity';

@Entity('tasks')
export class Task {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Index()
  @Column({ name: 'farm_id', type: 'uuid' })
  farmId: string;

  @ManyToOne(() => Farm, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'farm_id' })
  farm: Farm;

  // Optional scoping to a pond / crop. Kept as plain columns (no eager relation
  // needed) with FKs declared in the migration for referential integrity.
  @Index()
  @Column({ name: 'pond_id', type: 'uuid', nullable: true })
  pondId: string | null;

  @Index()
  @Column({ name: 'crop_id', type: 'uuid', nullable: true })
  cropId: string | null;

  @Column({ type: 'text' })
  title: string;

  @Column({ type: 'text', nullable: true })
  description: string | null;

  // FEED | WATER_TEST | SAMPLING | AERATOR_CHECK | MORTALITY_CHECK | HARVEST_PREP | OTHER
  @Column({ type: 'text', default: 'OTHER' })
  type: string;

  // 'open' | 'in_progress' | 'done' | 'verified' | 'cancelled'
  @Index()
  @Column({ type: 'text', default: 'open' })
  status: string;

  // 'low' | 'medium' | 'high'
  @Column({ type: 'text', default: 'medium' })
  priority: string;

  @Column({ name: 'due_date', type: 'date', nullable: true })
  dueDate: string | null;

  // Daily window the task should run in (e.g. feeding 06:00–07:00). TIME type.
  @Column({ name: 'time_window_start', type: 'time', nullable: true })
  timeWindowStart: string | null;

  @Column({ name: 'time_window_end', type: 'time', nullable: true })
  timeWindowEnd: string | null;

  // 'farm'     — the shared board; needs WRITE_MANAGEMENT to create or assign
  // 'personal' — a private note-to-self, visible ONLY to its creator, who is
  //              also its only ever assignee. Any member with READ may make one.
  @Column({ type: 'text', default: 'farm' })
  scope: string;

  // A recurrence TEMPLATE, not a to-do. Never returned by a task list; dated
  // instances are materialised from it on read (TasksService.materialise).
  @Index()
  @Column({ name: 'is_template', type: 'boolean', default: false })
  isTemplate: boolean;

  // RFC-5545-style rule. Templates use 'FREQ=DAILY' or 'FREQ=WEEKLY;BYDAY=<0-6>'.
  // Rows created before the template rewrite carry the old 'FREQ=DAILY;COUNT=90'
  // form; nothing parses those, they are ordinary dated tasks.
  @Column({ name: 'recurrence_rule', type: 'text', nullable: true })
  recurrenceRule: string | null;

  // Last date a template's series runs. NULL = forever.
  @Column({ name: 'recurrence_until', type: 'date', nullable: true })
  recurrenceUntil: string | null;

  // Instances point back at their template. (Series generated by the old eager
  // code point at their first row, which is itself a normal task — that is why
  // `isTemplate` and not `parentTaskId` is what identifies a template.)
  @Index()
  @Column({ name: 'parent_task_id', type: 'uuid', nullable: true })
  parentTaskId: string | null;

  // Who the task is for. NO ROWS MEANS EVERYONE IN SCOPE — see TaskAssignee.
  @OneToMany(() => TaskAssignee, (assignee) => assignee.task)
  assignees: TaskAssignee[];

  // Flattened `assignees` for the wire. Not a column; the service sets it on
  // every task it returns so callers never have to know about the join table.
  assigneeIds?: string[];

  @Column({ name: 'created_by_id', type: 'uuid', nullable: true })
  createdById: string | null;

  @Column({
    name: 'completed_at',
    type: 'timestamp with time zone',
    nullable: true,
  })
  completedAt: Date | null;

  // Manager verification of a completed task (blueprint §17.4).
  @Column({
    name: 'verified_at',
    type: 'timestamp with time zone',
    nullable: true,
  })
  verifiedAt: Date | null;

  @Column({ name: 'verified_by_id', type: 'uuid', nullable: true })
  verifiedById: string | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamp with time zone' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamp with time zone' })
  updatedAt: Date;
}
